import Link from 'next/link';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-slate-50">
            {/* Header */}
            <header className="bg-white border-b border-slate-200">
                <div className="max-w-4xl mx-auto px-4 py-6">
                    <Link href="/" className="text-madlen-500 hover:text-madlen-600 text-sm font-medium">
                        ← Back to Home
                    </Link>
                </div>
            </header>

            {/* Content */}
            <main className="max-w-4xl mx-auto px-4 py-12">
                <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
                <p className="text-slate-500 mb-8">Last updated: December 2025</p>

                <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 prose prose-slate max-w-none">
                    <h2>1. Acceptance of Terms</h2>
                    <p>
                        By accessing and using Madlen AI (&quot;the Service&quot;), you accept and agree to be bound by
                        these Terms of Service. If you do not agree to these terms, please do not use our Service.
                    </p>

                    <h2>2. Description of Service</h2>
                    <p>
                        Madlen AI is a free chat platform that provides access to various AI language models
                        through OpenRouter. The Service allows users to interact with AI models for text-based
                        conversations and, where supported, image analysis.
                    </p>

                    <h2>3. User Responsibilities</h2>
                    <p>You agree to:</p>
                    <ul>
                        <li>Use the Service only for lawful purposes</li>
                        <li>Not attempt to abuse, hack, or disrupt the Service</li>
                        <li>Not use the Service to generate harmful, illegal, or inappropriate content</li>
                        <li>Not share your account credentials with others</li>
                        <li>Comply with all applicable laws and regulations</li>
                    </ul>

                    <h2>4. AI-Generated Content</h2>
                    <p>
                        The responses generated by AI models may not always be accurate, complete, or appropriate.
                        You acknowledge that:
                    </p>
                    <ul>
                        <li>AI responses are for informational purposes only</li>
                        <li>You should verify important information from authoritative sources</li>
                        <li>We are not responsible for any decisions made based on AI responses</li>
                    </ul>

                    <h2>5. Privacy</h2>
                    <p>
                        Your use of the Service is also governed by our Privacy Policy. Please review our
                        Privacy Policy to understand our practices.
                    </p>

                    <h2>6. Limitation of Liability</h2>
                    <p>
                        The Service is provided &quot;as is&quot; without warranties of any kind. We shall not be liable
                        for any indirect, incidental, special, or consequential damages arising from your use
                        of the Service.
                    </p>

                    <h2>7. Changes to Terms</h2>
                    <p>
                        We reserve the right to modify these terms at any time. Continued use of the Service
                        after changes constitutes acceptance of the new terms.
                    </p>

                    <h2>8. Contact</h2>
                    <p>
                        For questions about these Terms of Service, please contact us at{' '}
                        <a href="mailto:support@madlen.ai" className="text-madlen-500">support@madlen.ai</a>.
                    </p>
                </div>
            </main>
        </div>
    );
}
